apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcrservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Peuin/mcrservice.git
    targetRevision: main
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: peuin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
